name: new-release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - name: Install emsdk
        run: |
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Start build
        run: |
          source $GITHUB_WORKSPACE/emsdk/emsdk_env.sh
          bash $GITHUB_WORKSPACE/compl/build.sh
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: build
          key: luauweb-build

  upload:
    needs: ["build", "create-release"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant_name: [Compiler, VM]
    steps:
    - name: Restore build
      uses: actions/cache@v4
      with:
        path: build
        key: luauweb-build
    - name: Copy built JS to dist/
      run: |
        mkdir -p dist
        cp build/compl/Luau.LuauWeb.${{ matrix.variant_name }}.js dist/LuauWeb.${{ matrix.variant_name }}.js
    - name: Commit and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/
        git commit -m "chore: update dist for ${{ matrix.variant_name }} ${{ needs.create-release.outputs.tag_name }}" || echo "No changes to commit"
        git push
