name: new-release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true

  setup-emsdk:
    needs: ["create-release"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache emsdk
        uses: actions/cache@v4
        with:
          path: emsdk
          key: emsdk-cache
      - uses: actions/checkout@v2
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - name: Install emsdk
        run: |
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

  build:
    needs: ["setup-emsdk"]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          source emsdk/emsdk_env.sh
          bash compl/build.sh
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: build
          key: luauweb-build

  upload:
    needs: ["build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant_name: [Compiler, VM]
    steps:
    - uses: actions/checkout@v2
    - name: Restore emsdk cache
      uses: actions/cache@v4
      with:
        path: emsdk
        key: emsdk-cache
    - name: Restore build
      uses: actions/cache@v4
      with:
        path: emsdk
        key: luauweb-build
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{ format('build/compl/Luau.LuauWeb.{}.js', matrix.variant_name) }} 
        asset_name: ${{ format('LuauWeb.{}.js', matrix.variant_name) }} 
        asset_content_type: application/octet-stream
